//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace ProductionBL.com.unitedcarexchange {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSProductionSoap", Namespace="http://tempuri.org/")]
    public partial class WSProduction : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCarsConnectionStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCarsCentralConnectionStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCarsTestConnectionStringOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSProduction() {
            this.Url = global::ProductionBL.Properties.Settings.Default.ProductionBL_com_unitedcarexchange_WSProduction;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCarsConnectionStringCompletedEventHandler GetCarsConnectionStringCompleted;
        
        /// <remarks/>
        public event GetCarsCentralConnectionStringCompletedEventHandler GetCarsCentralConnectionStringCompleted;
        
        /// <remarks/>
        public event GetCarsTestConnectionStringCompletedEventHandler GetCarsTestConnectionStringCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCarsConnectionString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCarsConnectionString() {
            object[] results = this.Invoke("GetCarsConnectionString", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCarsConnectionStringAsync() {
            this.GetCarsConnectionStringAsync(null);
        }
        
        /// <remarks/>
        public void GetCarsConnectionStringAsync(object userState) {
            if ((this.GetCarsConnectionStringOperationCompleted == null)) {
                this.GetCarsConnectionStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCarsConnectionStringOperationCompleted);
            }
            this.InvokeAsync("GetCarsConnectionString", new object[0], this.GetCarsConnectionStringOperationCompleted, userState);
        }
        
        private void OnGetCarsConnectionStringOperationCompleted(object arg) {
            if ((this.GetCarsConnectionStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCarsConnectionStringCompleted(this, new GetCarsConnectionStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCarsCentralConnectionString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCarsCentralConnectionString() {
            object[] results = this.Invoke("GetCarsCentralConnectionString", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCarsCentralConnectionStringAsync() {
            this.GetCarsCentralConnectionStringAsync(null);
        }
        
        /// <remarks/>
        public void GetCarsCentralConnectionStringAsync(object userState) {
            if ((this.GetCarsCentralConnectionStringOperationCompleted == null)) {
                this.GetCarsCentralConnectionStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCarsCentralConnectionStringOperationCompleted);
            }
            this.InvokeAsync("GetCarsCentralConnectionString", new object[0], this.GetCarsCentralConnectionStringOperationCompleted, userState);
        }
        
        private void OnGetCarsCentralConnectionStringOperationCompleted(object arg) {
            if ((this.GetCarsCentralConnectionStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCarsCentralConnectionStringCompleted(this, new GetCarsCentralConnectionStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCarsTestConnectionString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCarsTestConnectionString() {
            object[] results = this.Invoke("GetCarsTestConnectionString", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCarsTestConnectionStringAsync() {
            this.GetCarsTestConnectionStringAsync(null);
        }
        
        /// <remarks/>
        public void GetCarsTestConnectionStringAsync(object userState) {
            if ((this.GetCarsTestConnectionStringOperationCompleted == null)) {
                this.GetCarsTestConnectionStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCarsTestConnectionStringOperationCompleted);
            }
            this.InvokeAsync("GetCarsTestConnectionString", new object[0], this.GetCarsTestConnectionStringOperationCompleted, userState);
        }
        
        private void OnGetCarsTestConnectionStringOperationCompleted(object arg) {
            if ((this.GetCarsTestConnectionStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCarsTestConnectionStringCompleted(this, new GetCarsTestConnectionStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetCarsConnectionStringCompletedEventHandler(object sender, GetCarsConnectionStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCarsConnectionStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCarsConnectionStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetCarsCentralConnectionStringCompletedEventHandler(object sender, GetCarsCentralConnectionStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCarsCentralConnectionStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCarsCentralConnectionStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetCarsTestConnectionStringCompletedEventHandler(object sender, GetCarsTestConnectionStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCarsTestConnectionStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCarsTestConnectionStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591